version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    links:
      - php
    volumes:
      - ./src:/src
      - ./site.conf:/etc/nginx/conf.d/site.conf
  php:
    build: ./src
    volumes:
      - ./src:/src
    links:
      - db
  db:
    image: mariadb
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3306:3306"